// Code generated by gowsdl DO NOT EDIT.

package myservice

import (
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type In_bounds struct {
	XMLName xml.Name `xml:"http://webservice.bgcd.hwt.com in_bounds"`

	MessageType string `xml:"messageType,omitempty"`
}

type In_boundsResponse struct {
	XMLName xml.Name `xml:"http://webservice.bgcd.hwt.com in_boundsResponse"`

	Return_ string `xml:"return,omitempty"`
}

type FormateDate struct {
	XMLName xml.Name `xml:"http://webservice.bgcd.hwt.com formateDate"`

	Format string `xml:"format,omitempty"`
}

type FormateDateResponse struct {
	XMLName xml.Name `xml:"http://webservice.bgcd.hwt.com formateDateResponse"`

	Return_ string `xml:"return,omitempty"`
}

type InBoundsServicePortType interface {
	FormateDate(request *FormateDate) (*FormateDateResponse, error)

	In_bounds(request *In_bounds) (*In_boundsResponse, error)
}

type inBoundsServicePortType struct {
	client *soap.Client
}

func NewInBoundsServicePortType(client *soap.Client) InBoundsServicePortType {
	return &inBoundsServicePortType{
		client: client,
	}
}

func (service *inBoundsServicePortType) FormateDate(request *FormateDate) (*FormateDateResponse, error) {
	response := new(FormateDateResponse)
	err := service.client.Call("urn:formateDate", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *inBoundsServicePortType) In_bounds(request *In_bounds) (*In_boundsResponse, error) {
	response := new(In_boundsResponse)
	err := service.client.Call("urn:in_bounds", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}
