language: go

install:
  - go get -d -t -v ./... && go build -v ./...

go:
  - 1.13.x

os:
  - linux
  - osx

env:
  matrix:
    - GOARCH=amd64
    - GOARCH=386

script:
  - go vet ./...
  - go test ./... -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
